### ISSUE TITLE
not really something bad 

### ISSUE THREAD

**Issue by Brickwallvr** [SkyIsntFound1/I-Quit-GT-Modding.#1]
i just wanna say if you can please continue modding gorilla tag please it was my source of content on youtube and also i think a lot of other people want to mod too. So please bring back the gorilla tag SkyisntFound1 gorilla tag mods repository 

best reagards brickwallvr :)

**Comment by SkyIsntFound1** [comment]
I would if I could but I cant I was perm ip banned hwid on patched version so I cant return without buying a new headset sorry.
